# Generated by Django 2.2.2 on 2019-09-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0004_auto_20190928_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimatedDuration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
